
 # Versión de la configuración de Docker Compose
version: '3'

# Definición de servicios
services:
  # Servicio
  md-tp-pdf-python-services:
    # Configuración para construir la imagen del contenedor
    build:
      context: .
      dockerfile: Dockerfile
    # Nombre de la imagen resultante
    image: md-tp-pdf-python-image
    # Conexión a la red llamada 'luis'
    networks:
      - luis
    # Mapeo de puertos: Mapea el puerto 6002 del host al puerto 80 del contenedor
    ports:
      - 6601:80
    # Nombre del contenedor
    container_name: md-tp-pdf-python
    # Configuración para reiniciar siempre el contenedor
    restart: always

# Definición de redes
networks:
  # Definición de la red llamada 'luis'
  luis:
    # Especifica que la red es externa (puede haber sido creada fuera de este archivo)
    external: true