# Versión de la configuración de Docker Compose
version: '3'

# Definición de servicios
services:
  # Servicio llamado 'md-to-pdf-app-services'
  md-to-pdf-app-services:
    # Configuración para construir la imagen del contenedor
    build:
      context: .
      dockerfile: Dockerfile
    # Nombre de la imagen resultante
    image: md-to-pdf-app-image
    # Conexión a la red llamada 'luis'
    networks:
      - luis
    # Mapeo de puertos: Mapea el puerto 6600 del host al puerto 3000 del contenedor
    ports:
      - 6601:3000
    # Nombre del contenedor
    container_name: md-to-pdf-app
    # Configuración para reiniciar siempre el contenedor
    restart: always

# Definición de redes
networks:
  # Definición de la red llamada 'luis'
  luis:
    # Especifica que la red es externa (puede haber sido creada fuera de este archivo)
    external: true